site_name: SQLAlchemy-History
site_url: https://corridor.github.io/sqlalchemy-history/
site_author: Corridor

repo_name: sqlalchemy-history
repo_url: https://github.com/corridor/sqlalchemy-history
edit_uri: edit/master/docs
docs_dir: docs

theme:
  name: "readthedocs"

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: "sphinx"
  - awesome-pages
  - search
